/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Java8;

public class MainTest {
	/*
	 * @Test public void testSomeLibraryMethod() { Main classUnderTest = new Main();
	 * assertTrue("someLibraryMethod should return 'true'", classUnderTest.main());
	 * }
	 */
}
